package api

import (
	"encoding/json"
	"net/http"

	"github.com/lighttick/lighttick-backend/internal/auth"
	"github.com/lighttick/lighttick-backend/internal/db"
)

// SyncHandler handles offline-first sync operations
type SyncHandler struct {
	queries *db.Queries
}

// NewSyncHandler creates a new sync handler
func NewSyncHandler(queries *db.Queries) *SyncHandler {
	return &SyncHandler{queries: queries}
}

// Push handles POST /api/v1/sync/push
// Receives queued offline actions from the client
func (h *SyncHandler) Push(w http.ResponseWriter, r *http.Request) {
	userID := r.Context().Value(auth.UserIDKey).(string)

	var req struct {
		Actions []struct {
			Action    string      `json:"action"`    // complete/skip/defer/reschedule
			TaskID    int64       `json:"task_id"`
			Payload   interface{} `json:"payload"`   // action-specific data
			ClientTS  string      `json:"client_ts"` // RFC3339 timestamp
		} `json:"actions"`
		ClientVersion string `json:"client_version"` // local DB version for conflict detection
	}

	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		JSONError(w, http.StatusBadRequest, "INVALID_REQUEST", "invalid JSON body")
		return
	}

	if len(req.Actions) == 0 {
		JSONErrorWithField(w, http.StatusBadRequest, "MISSING_FIELD", "actions array is required", "actions")
		return
	}

	results := make([]map[string]interface{}, 0, len(req.Actions))

	for _, action := range req.Actions {
		if action.Action == "" || action.TaskID <= 0 {
			results = append(results, map[string]interface{}{
				"task_id": action.TaskID,
				"status":  "error",
				"reason":  "invalid action or task_id",
			})
			continue
		}

		// TODO: Process each action
		// 1. Check server state of the task
		// 2. Detect conflicts (server already modified since client_ts)
		// 3. If conflict: create sync_item with status=conflict, keep both versions
		// 4. If no conflict: apply the action, log to completion_history
		// 5. Create sync_item for audit trail

		results = append(results, map[string]interface{}{
			"task_id": action.TaskID,
			"action":  action.Action,
			"status":  "accepted", // or "conflict"
		})
	}

	// TODO: Queue sync_items for conflict resolution

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]interface{}{
		"synced":  len(req.Actions),
		"results": results,
	})
}

// Pull handles GET /api/v1/sync/pull
// Returns server-side changes since the client's last sync
func (h *SyncHandler) Pull(w http.ResponseWriter, r *http.Request) {
	userID := r.Context().Value(auth.UserIDKey).(string)

	// Optional: client provides last sync timestamp
	lastSync := r.URL.Query().Get("since")

	// TODO: Query changes since lastSync:
	// - Updated tasks (status changes, reschedules)
	// - New plans/tasks generated by AI
	// - Plan B suggestions
	// - Weekly summaries
	// - Conflict items that need user resolution

	_ = userID
	_ = lastSync

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]interface{}{
		"changes":     []interface{}{},
		"conflicts":   []interface{}{},
		"server_time": "not_implemented",
	})
}
