export const defaultAiNovelKickoffRecommendedPrompts = {
  "en-US": [
    "Write a progression fantasy about a sect exile.",
    "Write a restrained rebirth-revenge story.",
    "Plan a fast urban-fantasy novel with superpowered heroes.",
    "Write a tense rules-horror mystery.",
    "Write a light slice-of-life story with a speculative twist.",
    "Write an ensemble adventure with clear character growth.",
    "Write a restrained historical-intrigue revenge story.",
    "Write a fast cyberpunk urban-fantasy story.",
    "Write a campus-supernatural story sparked by one anomaly.",
    "Write an apocalypse-survival progression story that opens in conflict.",
  ],
  "zh-CN": [
    "写一本经典玄幻升级流，主角从被逐出宗门开始。",
    "写一个女频重生复仇故事，但情感线要克制一点。",
    "帮我规划一个轻松都市异能长篇，节奏要爽快。",
    "写一个规则怪谈方向的悬疑故事，气氛压迫一点。",
    "写一个轻松日常向故事，带一点反差脑洞。",
    "写一个群像冒险故事，每个人都有明显成长线。",
    "写一个古风权谋复仇故事，情绪克制但刀口很准。",
    "写一个赛博都市异能故事，节奏快一点。",
    "写一个校园超自然故事，从一个异常事件开始。",
    "写一个末世生存升级故事，开局就有强冲突。",
  ],
  "zh-TW": [
    "寫一部主角被逐出宗門後逆襲成長的王道奇幻。",
    "寫一部情感內斂的重生復仇故事。",
    "規劃一部節奏明快、讀來爽快的長篇都市異能小說。",
    "寫一部氣氛緊繃的規則怪談懸疑小說。",
    "寫一部輕鬆日常、卻帶有意外奇想轉折的故事。",
    "寫一部每位角色都有成長線的群像冒險故事。",
    "寫一部情感內斂、轉折縝密的歷史權謀復仇故事。",
    "寫一部節奏明快的賽博龐克都市異能故事。",
    "寫一部由一場異常事件揭開序幕的校園靈異故事。",
    "寫一部一開場就有衝突的末日生存成長故事。",
  ],
  "ja-JP": [
    "宗門を追放された主人公の成長譚を書こう。",
    "静かな熱を秘めた転生復讐譚を書こう。",
    "テンポよく読める長編の現代異能ものを考えよう。",
    "緊迫したルールホラーの謎解きを書こう。",
    "意外なSF的ひねりのある、軽やかな日常譚を書こう。",
    "全員に成長の見せ場がある群像冒険譚を作ろう。",
    "静かな熱と緻密な策謀が光る歴史復讐譚を書こう。",
    "疾走感のあるサイバーパンク現代異能譚を書こう。",
    "ひとつの異変から始まる学園怪異譚を書こう。",
    "冒頭から危機が迫る終末サバイバル成長譚を書こう。",
  ],
  "es-ES": [
    "Escribe una fantasía de progresión sobre un exiliado de una secta.",
    "Escribe una venganza tras renacer, con emociones contenidas.",
    "Planea fantasía urbana rápida con superpoderes.",
    "Escribe un misterio de terror regido por reglas.",
    "Escribe una historia cotidiana ligera con un giro especulativo.",
    "Escribe una aventura coral con arcos claros.",
    "Escribe intriga histórica de venganza, sobria y precisa.",
    "Escribe cyberpunk urbano con superpoderes y ritmo rápido.",
    "Escribe sobrenatural universitario desde una anomalía.",
    "Escribe supervivencia postapocalíptica con conflicto inicial.",
  ],
  "pt-BR": [
    "Escreva uma fantasia de progressão sobre um exilado de uma seita.",
    "Escreva uma história de vingança após renascer, com emoção contida.",
    "Planeje um romance de fantasia urbana rápido, com heróis superpoderosos.",
    "Escreva um mistério de terror guiado por regras.",
    "Escreva uma história leve do cotidiano com um toque especulativo.",
    "Escreva uma aventura em grupo com crescimento claro dos personagens.",
    "Escreva intriga histórica de vingança, precisa e contida.",
    "Escreva uma história cyberpunk urbana de superpoderes e ritmo rápido.",
    "Escreva uma história sobrenatural no campus que começa com uma anomalia.",
    "Escreva sobrevivência pós-apocalíptica com conflito inicial.",
  ],
  "ko-KR": [
    "문파에서 쫓겨난 주인공이 성장하는 정통 성장형 판타지를 써 보세요.",
    "절제된 감정선의 회귀 복수극을 써 보세요.",
    "빠른 전개로 시원하게 읽히는 장편 도시 이능물을 구상해 보세요.",
    "긴장감 넘치는 규칙 괴담 미스터리를 써 보세요.",
    "상상력 넘치는 반전이 있는 가벼운 일상물을 써 보세요.",
    "모든 인물이 뚜렷하게 성장하는 군상 모험담을 써 보세요.",
    "절제된 감정선과 치밀한 전개의 역사극 복수 이야기를 써 보세요.",
    "빠르게 전개되는 사이버펑크 도시 이능물을 써 보세요.",
    "한 번의 이상 현상에서 시작되는 학원 오컬트물을 써 보세요.",
    "첫 장부터 충돌이 터지는 아포칼립스 생존 성장물을 써 보세요.",
  ],
  "de-DE": [
    "Schreiben Sie Progressionsfantasy nach dem Exil aus einer Sekte.",
    "Schreiben Sie eine zurückhaltende Wiedergeburts-Rachegeschichte.",
    "Planen Sie schnelle Urban-Fantasy mit Superhelden.",
    "Schreiben Sie ein spannendes Horror-Mystery nach festen Regeln.",
    "Schreiben Sie Slice of Life mit spekulativer Wendung.",
    "Schreiben Sie ein Ensemble-Abenteuer mit klarer Figurenentwicklung.",
    "Schreiben Sie eine zurückhaltende historische Intrigen-Rachegeschichte.",
    "Schreiben Sie eine temporeiche Cyberpunk-Urban-Fantasy.",
    "Schreiben Sie Campus-Übernatürliches nach einem seltsamen Ereignis.",
    "Schreiben Sie postapokalyptisches Überleben mit frühem Konflikt.",
  ],
  "fr-FR": [
    "Écrivez une fantasy de progression où le héros est exilé d’une secte.",
    "Écrivez une vengeance après réincarnation, tout en retenue.",
    "Imaginez une urban fantasy aux superpouvoirs, rythmée.",
    "Écrivez un mystère horrifique régi par des règles.",
    "Écrivez une tranche de vie avec un twist spéculatif.",
    "Écrivez une aventure chorale aux arcs marqués.",
    "Écrivez une vengeance historique, sobre et précise.",
    "Écrivez un cyberpunk urbain aux superpouvoirs, nerveux.",
    "Écrivez du surnaturel sur campus, né d’un événement étrange.",
    "Écrivez une survie post-apo qui démarre dans le conflit.",
  ],
  "hi-IN": [
    "संप्रदाय से निकाले गए नायक की प्रोग्रेशन फ़ैंटेसी लिखें।",
    "संयत भावनाओं वाली पुनर्जन्म-प्रतिशोध कथा लिखें।",
    "तेज़ रफ्तार शहरी सुपरपावर उपन्यास रचें।",
    "तनावपूर्ण नियम-आधारित हॉरर रहस्य लिखें।",
    "SF-आधारित मोड़ वाली हल्की रोज़मर्रा की कहानी लिखें।",
    "स्पष्ट चरित्र-विकास वाली सामूहिक साहसिक कथा लिखें।",
    "संयत भावनाओं वाली ऐतिहासिक साज़िश-प्रतिशोध कथा लिखें।",
    "तेज़ रफ्तार साइबरपंक शहरी सुपरपावर कथा लिखें।",
    "एक असामान्य घटना से शुरू होने वाली कैंपस अलौकिक कथा लिखें।",
    "तुरंत संघर्ष से शुरू होने वाली सर्वनाश-उपरांत जीवित रहने की कथा लिखें।",
  ],
  "id-ID": [
    "Tulis fantasi progresi tentang tokoh yang diusir dari sekte.",
    "Tulis kisah balas dendam reinkarnasi yang terkendali.",
    "Rancang cerita kekuatan super urban yang serba cepat.",
    "Tulis misteri horor bertema aturan yang mencekam.",
    "Tulis kisah keseharian ringan dengan kejutan fantastis.",
    "Tulis petualangan ansambel dengan perkembangan tiap tokoh.",
    "Tulis balas dendam dalam intrik sejarah dengan emosi terkendali.",
    "Tulis cerita cyberpunk urban dengan kekuatan super dan tempo cepat.",
    "Tulis kisah supranatural kampus dari satu kejadian ganjil.",
    "Tulis kisah bertahan hidup pascaapokalips dengan konflik langsung.",
  ],
  "it-IT": [
    "Scrivi una fantasy di crescita dopo l’esilio dalla setta.",
    "Scrivi una vendetta dopo la rinascita, dai toni misurati.",
    "Progetta urban fantasy con superpoteri e ritmo veloce.",
    "Scrivi un mystery horror regolato da regole ferree.",
    "Scrivi uno slice of life con un twist speculativo.",
    "Scrivi un’avventura corale con archi chiari.",
    "Scrivi intrighi storici di vendetta, sobri e precisi.",
    "Scrivi cyberpunk urbano con superpoteri e ritmo serrato.",
    "Scrivi soprannaturale universitario da un fatto anomalo.",
    "Scrivi una storia post-apocalittica in conflitto.",
  ],
  "tr-TR": [
    "Mezhepten atılan kahramanla bir gelişim fantastiği yazın.",
    "Duygusu ölçülü bir yeniden doğuş intikamı yazın.",
    "Hızlı tempolu, süper güçlü şehir fantastiği planlayın.",
    "Kurallarla yönetilen karanlık bir korku gizemi yazın.",
    "Spekülatif sürprizli bir gündelik hikâye yazın.",
    "Karakter gelişimli bir topluluk macerası yazın.",
    "Tarihî, ölçülü bir intikam hikâyesi yazın.",
    "Hızlı tempolu, süper güçlü siberpunk şehir hikâyesi yazın.",
    "Tuhaf bir olayla başlayan doğaüstü kampüs hikâyesi yazın.",
    "Çatışmayla açılan kıyamet sonrası hikâye yazın.",
  ],
  "vi-VN": [
    "Viết fantasy tu luyện về nhân vật bị trục xuất khỏi tông môn.",
    "Viết truyện báo thù tái sinh, cảm xúc tiết chế.",
    "Lên ý tưởng truyện dị năng đô thị nhịp nhanh.",
    "Viết bí ẩn kinh dị theo luật lệ, bầu không khí ngột ngạt.",
    "Viết truyện đời thường nhẹ nhàng với cú twist kỳ ảo.",
    "Viết phiêu lưu nhóm, mỗi nhân vật đều phát triển rõ nét.",
    "Viết truyện báo thù với những âm mưu lịch sử và cảm xúc tiết chế.",
    "Viết cyberpunk dị năng đô thị nhịp nhanh.",
    "Viết truyện siêu nhiên học đường từ một sự kiện lạ.",
    "Viết sinh tồn hậu tận thế, mở màn bằng xung đột.",
  ],
  "th-TH": [
    "เขียนแฟนตาซีสายเติบโตของตัวเอกที่ถูกขับออกจากสำนัก",
    "เขียนเรื่องแก้แค้นหลังเกิดใหม่ที่อารมณ์สุขุม",
    "วางพล็อตนิยายพลังพิเศษในเมือง จังหวะเร็ว",
    "เขียนลึกลับสยองขวัญตามกฎ บรรยากาศกดดัน",
    "เขียนชีวิตประจำวันเบาๆ ที่มีพลิกผันเหนือคาด",
    "เขียนผจญภัยแบบทีม ตัวละครเติบโตชัดเจน",
    "เขียนแก้แค้นท่ามกลางเล่ห์กลประวัติศาสตร์ อารมณ์สุขุม",
    "เขียนไซเบอร์พังก์พลังพิเศษในเมือง จังหวะเร็ว",
    "เขียนเหนือธรรมชาติในมหาวิทยาลัย จากเหตุผิดปกติหนึ่งครั้ง",
    "เขียนเอาตัวรอดหลังวันสิ้นโลก เปิดด้วยความขัดแย้ง",
  ],
  "pl-PL": [
    "Napisz fantasy progresywną po wygnaniu z sekty.",
    "Napisz zemstę po odrodzeniu, z powściągliwymi emocjami.",
    "Zaplanuj miejskie fantasy z supermocami i szybkim tempem.",
    "Napisz mroczną zagadkę grozy opartą na zasadach.",
    "Napisz lekką obyczajówkę ze spekulatywnym twistem.",
    "Napisz przygodę zespołową z wyraźnymi łukami postaci.",
    "Napisz historyczną intrygę zemsty: oszczędną i precyzyjną.",
    "Napisz szybką miejską historię cyberpunk z supermocami.",
    "Napisz kampusowy horror nadprzyrodzony.",
    "Napisz postapo o przetrwaniu z natychmiastowym konfliktem.",
  ],
  "nl-NL": [
    "Schrijf progression fantasy na verbanning uit een sekte.",
    "Schrijf een ingetogen wraakverhaal na een wedergeboorte.",
    "Plan een snelle urbanfantasyroman met helden met superkrachten.",
    "Schrijf een spannend horrormysterie volgens vaste regels.",
    "Schrijf een luchtig slice-of-lifeverhaal met een speculatieve wending.",
    "Schrijf een ensemble-avontuur met duidelijke karakterontwikkeling.",
    "Schrijf een ingetogen historisch wraakverhaal vol intrige.",
    "Schrijf een snelle cyberpunk-urbanfantasy.",
    "Schrijf een bovennatuurlijk campusverhaal na een vreemde gebeurtenis.",
    "Schrijf postapocalyptische overleving met een vroeg conflict.",
  ],
  "sv-SE": [
    "Skriv en progression fantasy om en sektutstött person.",
    "Skriv en lågmäld berättelse om återfödelse och hämnd.",
    "Planera urban fantasy med superkrafter och högt tempo.",
    "Skriv ett mörkt skräckmysterium styrt av regler.",
    "Skriv en lätt vardagsberättelse med en spekulativ vändning.",
    "Skriv ett ensembleäventyr med tydliga utvecklingsbågar.",
    "Skriv historiska hämndintriger, lågmält och precist.",
    "Skriv snabb urban cyberpunk med superkrafter.",
    "Skriv campusmystik efter en märklig händelse.",
    "Skriv apokalypsöverlevnad med omedelbar konflikt.",
  ],
  "bn-BD": [
    "গোষ্ঠী থেকে বহিষ্কৃত নায়ককে নিয়ে বিকাশধর্মী ফ্যান্টাসি লিখুন।",
    "সংযত আবেগের পুনর্জন্ম-প্রতিশোধের গল্প লিখুন।",
    "দ্রুতগতির শহুরে সুপারপাওয়ার গল্প লিখুন।",
    "টানটান নিয়মভিত্তিক ভৌতিক রহস্য লিখুন।",
    "কল্পনাপ্রসূত মোড়ের হালকা জীবনঘনিষ্ঠ গল্প লিখুন।",
    "সব চরিত্রের বিকাশসহ দলগত অভিযান লিখুন।",
    "সংযত আবেগের ঐতিহাসিক ষড়যন্ত্র-প্রতিশোধ লিখুন।",
    "দ্রুতগতির সাইবারপাঙ্ক শহুরে সুপারপাওয়ার গল্প লিখুন।",
    "অস্বাভাবিক ঘটনা দিয়ে শুরু হওয়া ক্যাম্পাসের অতিপ্রাকৃত গল্প লিখুন।",
    "তাৎক্ষণিক সংঘর্ষে শুরু প্রলয়োত্তর বেঁচে থাকার গল্প লিখুন।",
  ],
  "sw-KE": [
    "Andika fantasia ya ukuaji kuhusu shujaa aliyefukuzwa katika dhehebu.",
    "Andika kisasi cha kuzaliwa upya chenye hisia zilizodhibitiwa.",
    "Panga hadithi ya nguvu za ajabu mijini yenye mwendo wa kasi.",
    "Andika fumbo la kutisha linalofuata sheria, lenye msisimko.",
    "Andika hadithi nyepesi ya maisha yenye mgeuko wa kubuni.",
    "Andika hadithi ya matukio ya kundi lenye ukuaji wazi wa wahusika.",
    "Andika kisasi cha njama za kihistoria chenye hisia zilizodhibitiwa.",
    "Andika hadithi ya cyberpunk yenye nguvu za ajabu mijini.",
    "Andika hadithi ya ajabu chuoni inayoanza na tukio lisilo la kawaida.",
    "Andika hadithi ya kuishi baada ya maangamizi yenye mgogoro wa haraka.",
  ],
} as const;

export const defaultAiNovelLegacyRecommendedPrompts =
  defaultAiNovelKickoffRecommendedPrompts["zh-CN"];
