import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  route("login", "routes/login.tsx"),
  layout("routes/console-layout.tsx", [
    index("routes/home.tsx"),
    route("apps", "routes/apps.tsx"),
    route("auth-rate-limits", "routes/auth-rate-limits.tsx"),
    route("config", "routes/config.tsx"),
    route("ai-routing", "routes/ai-routing.tsx"),
    route("lighttick", "routes/lighttick.tsx"),
    route("bodylog", "routes/bodylog.tsx"),
    route("bodylog/records", "routes/bodylog-records.tsx"),
    route("bodylog/groups", "routes/bodylog-groups.tsx"),
    route("bodylog/habit-templates", "routes/bodylog-habit-templates.tsx"),
    route("feedback", "routes/feedback.tsx"),
    route("billing-orders", "routes/ainovel-billing-orders.tsx"),
    route("conversation-records", "routes/conversation-records.tsx"),
    route("conversation-history", "routes/conversation-history.tsx"),
    route("remote-log-pull", "routes/remote-log-pull.tsx"),
    route("remote-log-pull/tasks/:taskId", "routes/remote-log-pull-task.tsx"),
    route("mail", "routes/mail.tsx"),
    route("sms", "routes/sms.tsx"),
    route("passwords", "routes/passwords.tsx"),
    route("content-safety", "routes/content-safety.tsx"),
    route("getui-gy", "routes/getui-gy.tsx"),
    route("llm", "routes/llm.tsx"),
    route("release-updates", "routes/release-updates.tsx"),
  ]),
] satisfies RouteConfig;
