

export type AppStatus = "ACTIVE" | "BLOCKED";
export type JoinMode = "AUTO" | "INVITE_ONLY";
export type UserStatus = "ACTIVE" | "BLOCKED";
export type AppUserStatus = "ACTIVE" | "BLOCKED" | "DELETED";
export type AccountRegion = "CN" | "GLOBAL" | "UNKNOWN";
export type RoleStatus = "ACTIVE" | "BLOCKED";
export type PermissionStatus = "ACTIVE" | "BLOCKED";
export type FileStatus = "PENDING" | "CONFIRMED" | "EXPIRED";
export type NotificationStatus =
  | "PENDING"
  | "QUEUED"
  | "SENT"
  | "FAILED"
  | "ENQUEUE_FAILED";
export type ClientType = "web" | "app";
export type EventName = "page_view" | "page_leave" | "page_heartbeat";
export type Platform = "web" | "ios" | "android";
export type TencentSesRegion = "ap-guangzhou" | "ap-hongkong";
export type LlmRoutingStrategy = "auto" | "fixed";
export type LlmModelKind = "chat" | "embedding";
export type LlmMetricsRange = "24h" | "7d" | "30d";
export type LlmSmokeTestStatus = "success" | "failed" | "skipped";
export type ContentSafetyCheckSource = "business" | "admin_test";
export type ContentSafetyCheckMethod =
  | "disabled"
  | "keyword"
  | "llm"
  | "aliyun"
  | "failed_open";
export type ContentSafetyDecision = "pass" | "block" | "failed_open";
export type ErrorCode =
  | "AI_DECRYPT_FAILED"
  | "AI_EMBEDDING_INPUT_INVALID"
  | "AI_ENCRYPT_FAILED"
  | "AI_INPUT_CONTENT_SENSITIVE"
  | "AI_RESPONSE_FORMAT_INVALID"
  | "AI_SCENE_NOT_SUPPORTED"
  | "AI_UNKNOWN_KEY_ID"
  | "AI_UNSUPPORTED_ALGORITHM"
  | "AI_UPSTREAM_AUTH_FAILED"
  | "AI_UPSTREAM_BAD_GATEWAY"
  | "AI_UPSTREAM_CONFIG_INVALID"
  | "AI_UPSTREAM_INVALID_REQUEST"
  | "AI_UPSTREAM_QUOTA_EXHAUSTED"
  | "AI_UPSTREAM_RATE_LIMITED"
  | "AI_UPSTREAM_RESPONSE_INVALID"
  | "AI_UPSTREAM_TIMEOUT"
  | "ADMIN_AUTH_REQUIRED"
  | "ADMIN_BASIC_AUTH_REQUIRED"
  | "ADMIN_INVALID_CREDENTIAL"
  | "ADMIN_CONFIG_INVALID_JSON"
  | "ADMIN_APP_ALREADY_EXISTS"
  | "ADMIN_APP_ID_RESERVED"
  | "ADMIN_APP_DELETE_REQUIRES_EMPTY_CONFIG"
  | "ADMIN_EMAIL_SERVICE_INVALID"
  | "ADMIN_I18N_INVALID"
  | "ADMIN_LLM_SERVICE_INVALID"
  | "ADMIN_PASSWORD_INVALID"
  | "ADMIN_RATE_LIMITED"
  | "ADMIN_SENSITIVE_OPERATION_REQUIRED"
  | "ADMIN_SENSITIVE_CODE_REQUIRED"
  | "ADMIN_SENSITIVE_CODE_INVALID"
  | "ADMIN_SENSITIVE_RATE_LIMITED"
  | "AUTH_INVALID_CREDENTIAL"
  | "AUTH_BEARER_REQUIRED"
  | "AUTH_INVALID_TOKEN"
  | "AUTH_REFRESH_TOKEN_REQUIRED"
  | "AUTH_REFRESH_TOKEN_REVOKED"
  | "AUTH_VERIFICATION_CODE_REQUIRED"
  | "AUTH_VERIFICATION_CODE_INVALID"
  | "AUTH_ACCOUNT_ALREADY_EXISTS"
  | "AUTH_ACCOUNT_DELETE_CONFIRMATION_INVALID"
  | "AUTH_ACCOUNT_NOT_FOUND"
  | "AUTH_PASSWORD_ALREADY_SET"
  | "AUTH_PASSWORD_NOT_SET"
  | "AUTH_RATE_LIMITED"
  | "AUTH_QR_LOGIN_TOKEN_REQUIRED"
  | "AUTH_QR_LOGIN_INVALID"
  | "AUTH_QR_LOGIN_EXPIRED"
  | "AUTH_QR_LOGIN_ALREADY_USED"
  | "AUTH_ONE_CLICK_TOKEN_INVALID"
  | "AUTH_APP_SCOPE_MISMATCH"
  | "AUTH_LOGIN_TEMPORARILY_LOCKED"
  | "AUTH_USER_BLOCKED"
  | "APP_NOT_FOUND"
  | "APP_BLOCKED"
  | "APP_JOIN_INVITE_REQUIRED"
  | "APP_MEMBER_BLOCKED"
  | "APP_MEMBER_DELETED"
  | "IAM_PERMISSION_DENIED"
  | "FILE_ACCESS_DENIED"
  | "EMAIL_SERVICE_NOT_CONFIGURED"
  | "EMAIL_PROVIDER_REQUEST_FAILED"
  | "SMS_SERVICE_NOT_CONFIGURED"
  | "SMS_SERVICE_MISSING_SECRET_ID"
  | "SMS_SERVICE_MISSING_SECRET_KEY"
  | "SMS_SERVICE_MISSING_SDK_APP_ID"
  | "SMS_SERVICE_MISSING_TEMPLATE_ID"
  | "SMS_SERVICE_MISSING_SIGN_NAME"
  | "SMS_PROVIDER_REQUEST_FAILED"
  | "ONE_CLICK_SERVICE_NOT_CONFIGURED"
  | "ONE_CLICK_PROVIDER_REQUEST_FAILED"
  | "CAPTCHA_SERVICE_NOT_CONFIGURED"
  | "CAPTCHA_PROVIDER_REQUEST_FAILED"
  | "LLM_MODEL_NOT_FOUND"
  | "LLM_SERVICE_NOT_CONFIGURED"
  | "LLM_ROUTE_NOT_AVAILABLE"
  | "LLM_PROVIDER_CONTENT_SENSITIVE"
  | "LLM_PROVIDER_REQUEST_FAILED"
  | "LLM_PROVIDER_RESPONSE_INVALID"
  | "LOG_UNSUPPORTED_ENCRYPTION"
  | "LOG_DECRYPT_FAILED"
  | "LOG_DECOMPRESS_FAILED"
  | "LOG_INVALID_NDJSON"
  | "LOG_CLAIM_MISMATCH"
  | "LOG_CLAIM_EXPIRED"
  | "LOG_TASK_ALREADY_COMPLETED"
  | "LOG_TASK_MISMATCH"
  | "LOG_PAYLOAD_TOO_LARGE"
  | "REQ_INVALID_BODY"
  | "REQ_INVALID_HEADER"
  | "REQ_INVALID_QUERY"
  | "REQ_INVALID_EVENT"
  | "REQ_DATE_RANGE_INVALID"
  | "SYS_INTERNAL_ERROR";
