import assert from "node:assert/strict";
import test from "node:test";
import {readFileSync} from "node:fs";
import Ajv2020 from "ajv/dist/2020.js";
import addFormats from "ajv-formats";
import * as contracts from "../../src/generated/openapi/public-contracts.generated.ts";
import { buildDefaultSeed } from "../../src/infrastructure/database/prisma/default-seed.ts";
import { createApplication } from "../support/create-test-application.ts";
import { LightTickAiRunner } from "../../src/modules/lighttick/ai/lighttick-ai-runner.ts";
import { LightTickWorker } from "../../src/modules/lighttick/lighttick-worker.ts";

test("planning HTTP contracts, auth, gate, queue, replay and explicit confirmation",async()=>{
  const seed=buildDefaultSeed(undefined,{includeLightTick:true});
  for(const userId of ["user_alice","user_bob"]) seed.appUsers.push({id:"planning_"+userId,appId:"lighttick",userId,status:"ACTIVE",accountRegion:"UNKNOWN",joinedAt:new Date().toISOString()});
  const app=await createApplication({seed,lighttickEnabled:true});
  const runtime=app.services.lighttickRuntime, owner={appId:"lighttick" as const,userId:"user_alice"};
  const headers={authorization:"Bearer "+app.services.tokenService.issueAccessToken(owner.userId,"lighttick")};
  const call=(path:string,method:any="GET",body?:unknown,key="operation",override=headers)=>app.app.handle({method,path:"/api/v1/lighttick/planning-sessions"+path,body,headers:{...override,"idempotency-key":key}});
  runtime.planningEnabled=false;
  assert.equal((await call("","POST",{goal_id:"none"})).statusCode,503);
  runtime.planningEnabled=true;
  assert.equal((await call("","POST",{goal_id:"none"},"auth",{} as any)).statusCode,401);
  const goal=await runtime.goals.create(owner,{title:"做一个网页",constraints:{weekly_available_minutes:30}});
  const created=await call("","POST",{goal_id:goal.id},"create");
  assert.equal(created.statusCode,201);
  const ajv=new Ajv2020({strict:false});addFormats(ajv);
  const check=(schema:object,data:unknown)=>{const validate=ajv.compile(schema);assert.equal(validate(JSON.parse(JSON.stringify(data))),true,JSON.stringify(validate.errors));};
  check(contracts.LightTickPlanningMutationEnvelopeSchema,created.body);
  let session=(created.body.data as any).session;
  assert.equal((await call("/"+session.id,"GET",undefined,"read",{authorization:"Bearer "+app.services.tokenService.issueAccessToken("user_bob","lighttick")})).statusCode,404);
  assert.equal((await call("","POST",{goal_id:goal.id,thread_id:"foreign"},"injection")).statusCode,400);
  const patch={base_version:session.version,fields:{period_start:{value:"2026-09-13",source:"user"},period_end:{value:"2026-09-19",source:"confirmed"}}};
  check(contracts.LightTickPlanningContextRequestSchema,patch);
  const ready=await call("/"+session.id+"/context","POST",patch,"context",{...headers,"x-http-method-override":"PATCH"} as any);assert.equal(ready.statusCode,200);session=(ready.body.data as any).session;
  const fixtures=JSON.parse(readFileSync(new URL("../../api-contracts/fixtures/lighttick/planning-errors.json",import.meta.url),"utf8"));
  for(const fixture of fixtures.cases){const failed=await call("/"+session.id+fixture.suffix,fixture.method,fixture.body,fixture.name);assert.equal(failed.statusCode,fixture.status,fixture.name);assert.equal(failed.body.code,fixture.code,fixture.name);}
  const draft={base_version:session.version,context_revision:session.context_revision,deep_planning:true};
  const accepted=await call("/"+session.id+"/drafts","POST",draft,"draft");assert.equal(accepted.statusCode,202);
  assert.deepEqual((await call("/"+session.id+"/drafts","POST",draft,"draft")).body.data,accepted.body.data);
  runtime.worker=new LightTickWorker(new LightTickAiRunner(runtime.repository,{complete:async()=>({provider:"fake",providerModel:"fake",text:JSON.stringify({tasks:[{title:"运行网页并记录结果",estimated_minutes:10}]})})} as any));
  await app.queue.processDueJobs(job=>runtime.worker!.process(job),new Date("2030-01-01"));
  const fetched=await call("/"+session.id);check(contracts.LightTickPlanningEnvelopeSchema,fetched.body);
  session=(fetched.body.data as any);assert.equal(session.status,"draft_ready");
  const plan=await runtime.repository.getPlan(owner,session.draft_plan_id);
  const confirmation={base_version:session.version,context_revision:session.context_revision,draft_plan_id:plan!.id,plan_version:plan!.version};
  check(contracts.LightTickPlanningConfirmRequestSchema,confirmation);
  const done=await call("/"+session.id+"/confirm","POST",confirmation,"confirm");assert.equal(done.statusCode,200);
  assert.equal((done.body.data as any).session.status,"confirmed");
  assert.deepEqual((await call("/"+session.id+"/confirm","POST",confirmation,"confirm")).body.data,done.body.data);
  assert.equal((await runtime.repository.listTasks(owner)).length,1);
  assert.equal((await call("/"+session.id+"/confirm","POST",confirmation,"other-device")).statusCode,409);
});
